# There is the new command "version" in buildew script. # there is the cmd for run server.

diff --git a/buildew b/buildew
--- a/buildew
+++ b/buildew
@@ -1,11 +1,12 @@
 #!/bin/bash
 
-GO=go
+GOLANG_VERSION=1.21.2
+
 COMMAND=$1
 while [[ "$#" -gt 0 ]]; do
     case $1 in
-    --go-version)
-        GO_VERSION="$2"
+    --golang-version)
+        GOLANG_VERSION="$2"
         shift
         shift
         ;;
@@ -18,74 +19,75 @@ while [[ "$#" -gt 0 ]]; do
     shift
 done
 
-# MODULES
-MODULES=(utils models client services .)
-
-if [ $COMMAND == "test" ]; then
-    echo Start all tests:
-    $GO test
+if [[ "$(go version)" =~ .*([0-9]+\.[0-9]+\.[0-9]+).* ]]; then
+    ACTUAL_GOLANG_VERSION="${BASH_REMATCH[1]}"
+    if [ "$ACTUAL_GOLANG_VERSION" != "$GOLANG_VERSION" ]; then
+        echo WARNING:
+        echo Desired Go lang version is $GOLANG_VERSION
+        echo Actual Go lang version is $ACTUAL_GOLANG_VERSION
+    fi
 fi
 
-if [ $COMMAND == "tidy" ]; then
-    echo Start tidy for all modules:
-    for module in "${MODULES[@]}"; do
-        echo -n Tidy $module
-        CD=$PWD
-        cd $module
-        $GO mod tidy
-        result=$?
-        cd $CD
-        if [ $result -ne 0 ]; then
-            echo -e '\033[01;31m' " Error"
-            echo -e -n '\033[00m'
-        else
-            echo -e '\033[01;32m' " Done"
-            echo -e -n '\033[00m'
+# ========================= LOCAL ENVIRONMENT VARIABLES =======================
+
+if [ -f '.env' ]; then
+    echo Use .env file to read sensitive information
+    while IPS='=' read -r key _; do
+        if [ "${key}" != "" ] && [[ ! "${key}" =~ .*#.* ]]; then
+            eval "export ${key}"
         fi
-    done
+    done <'.env'
+else
+    # REGENERATE SENSITIVE INFO FROM TEMPLATE
+    cat >'.env' <<EOF
+# Golang package version (without v)
+S2D3_PACKAGE_VERSION=0.0.0
+EOF
 fi
 
-if [ "$COMMAND" == "version" ]; then
-    echo Set version:
-    # Remove initial v for prevent vv issue
+# Warn: S2D3_PACKAGE_VERSION read from .env file
 
-    # TODO: change dependencies for all subpackages (client, models, services, etc...)
+# =============================================================================
 
-    TAG_SUFFIX=${1#v}
-
-    git tag "v$TAG_SUFFIX"
-    git push origin "v$TAG_SUFFIX"
-
-    SUB_MODULES=('utils' 'models' 'services' 'client')
-    for SUB_MODULE in "${SUB_MODULES[@]}"; do
-        git tag "$SUB_MODULE/v$TAG_SUFFIX"
-        git push origin "$SUB_MODULE/v$TAG_SUFFIX"
-    done
+if [ "$COMMAND" == "build" ]; then
+    docker build -f Dockerfile -t "usalko/s2d3:$S2D3_PACKAGE_VERSION" . --progress=plain
 fi
 
 if [ "$COMMAND" == "publish" ]; then
-    TAG_SUFFIX=${1#v}
-    SUB_MODULES=('utils' 'models' 'services' 'client')
-    for SUB_MODULE in "${SUB_MODULES[@]}"; do
-        GOPROXY=proxy.golang.org go list -m "github.com/usalko/s2d3/$SUB_MODULE@v$TAG_SUFFIX"
-    done
-    GOPROXY=proxy.golang.org go list -m "github.com/usalko/s2d3@v$TAG_SUFFIX"
+    IMAGE="usalko/s2d3:$S2D3_PACKAGE_VERSION"
+    docker push "$IMAGE" || {
+        echo "Line 12: Error in push to dockerhub image $IMAGE... Exit..."
+        exit 1
+    }
 fi
 
-# ======================================= GENERAL INFO ============================================
-if [ "$COMMAND" == "modules" ] || [ "$COMMAND" == "module" ]; then
-    echo There are available modules:
-    for MODULE in "${MODULES[@]}"; do
-        echo ' - ' $MODULE
-    done
+if [ "$COMMAND" == "test" ]; then
+    go test s2d3
+fi
+
+if [ "$COMMAND" == "version" ]; then
+    echo Previous version "$S2D3_PACKAGE_VERSION"
+    echo Please enter new version \(format: x.y.z, where x, y and z are integer numbers\)
+    read NEW_S2D3_PACKAGE_VERSION
+
+    # Check version format
+    [[ $NEW_S2D3_PACKAGE_VERSION =~ \d+\.\d+\.\d+ ]] || ( echo ERROR: wrong version format; exit 1 )
+
+    # Replace versions in go.mod files
+    find . -name go.mod -exec sed -i "s/$S2D3_PACKAGE_VERSION/$NEW_S2D3_PACKAGE_VERSION/g" '{}' \;
+    [ $? -eq 0 ] || ( echo Fail replace version in go.mod files; exit 1 ) 
+
+    # Replace version in README.md
+    sed -i "s/$S2D3_PACKAGE_VERSION/$NEW_S2D3_PACKAGE_VERSION/g" ./README.md
+    [ $? -eq 0 ] || ( echo Fail replace version in README.md; exit 1 ) 
+
+    # Replace version in .env file
+    # Replace version in README.md
+    sed -i "s/$S2D3_PACKAGE_VERSION/$NEW_S2D3_PACKAGE_VERSION/g" ./README.md
 fi
 
 # =================================================================================================
 
-AVAILABLE_COMMANDS="test tidy version publish modules"
+AVAILABLE_COMMANDS="build publish test version"
 echo ''
 [[ $AVAILABLE_COMMANDS =~ (^| )$COMMAND($| ) ]] && echo 'Ok' || (echo 'Unknown command: ' "$COMMAND" && echo 'Available commands are: ' "$AVAILABLE_COMMANDS")
-
-# Useful references:
-# Submodule issues: @see https://stackoverflow.com/questions/67678203/why-does-go-get-fail-with-invalid-version-unknown-revision
-# ....
